# Generated by Django 3.1.6 on 2021-04-15 18:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cav_map', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumpost',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 15, 18, 18, 45, 371369), verbose_name='date published'),
            preserve_default=False,
        ),
    ]
