# Generated by Django 3.1.7 on 2021-04-04 23:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cav_map', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='x_cord',
            field=models.CharField(default='0.0', max_length=100),
        ),
        migrations.AddField(
            model_name='class',
            name='y_cord',
            field=models.CharField(default='0.0', max_length=100),
        ),
        migrations.AddField(
            model_name='classschedule',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
