# Generated by Django 3.1.7 on 2021-04-16 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cav_map', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='x',
        ),
        migrations.RemoveField(
            model_name='class',
            name='y',
        ),
    ]
