# Generated by Django 3.1.7 on 2021-04-06 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cav_map', '0002_auto_20210404_1906'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Mary', max_length=52)),
                ('email', models.CharField(default='nope@null.com', max_length=122)),
            ],
        ),
        migrations.RenameField(
            model_name='class',
            old_name='x_cord',
            new_name='x',
        ),
        migrations.RenameField(
            model_name='class',
            old_name='y_cord',
            new_name='y',
        ),
        migrations.AlterField(
            model_name='class',
            name='className',
            field=models.CharField(default='New Class', max_length=122),
        ),
    ]
