# Generated by Django 3.1.7 on 2021-04-07 18:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cav_map', '0003_auto_20210406_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='classschedule',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cav_map.student'),
        ),
    ]
