# Generated by Django 3.1.6 on 2021-04-16 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cav_map', '0004_auto_20210416_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='urls',
        ),
    ]
