# Generated by Django 3.1.7 on 2021-04-23 17:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cav_map', '0006_route_urls'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumpost',
            name='likes',
            field=models.ManyToManyField(related_name='forum_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
